<?php


namespace App\Controller;

use App\Repository\LecturerRepository;
use App\Services\AbstractCrudController;
use App\Services\AbstractJsonView;
use App\Services\CrudServiceInterface;
use App\Services\JsonView;
use App\Services\LecturerService;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class LecturerCrudController
 * @package App\Controller
 * @Route("lecturer/")
 */
class LecturerCrudController extends AbstractCrudController
{
    private $lecturerRepository;

    public function __construct(LecturerRepository $lecturerRepository
    )
    {
        $this->lecturerRepository = $lecturerRepository;
    }

    public static function getSubscribedServices()
    {
        return array_merge(
            parent::getSubscribedServices(),
            [
                LecturerService::class
            ]
        )
            ; // TODO: Change the autogenerated stub
    }

    /**
     * @Route("all/", methods={"GET"})
     */
    public function getAll()
    {
        $data = $this->getItemService()->findAllandHiddenPass();
        return $this->json(
            [
                'lecturers' => $data
            ]
        );
    }

    protected function getItemService(): CrudServiceInterface
    {
        return $this->container->get(LecturerService::class);
    }

    protected function getJsonView(): AbstractJsonView
    {
        return new JsonView();
    }

}
